<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Wording.ico</ApplicationIcon>
    <AssemblyName>Wording</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" />
    <Resource Include="Assets\Wording.ico" />
    <Resource Include="Assets\Wording.png" />
    <ProjectReference Include="..\Wording.Core\Wording.Core.csproj" />
    <ProjectReference Include="..\Wording.Infrastructure\Wording.Infrastructure.csproj" />
  </ItemGroup>
</Project>
